=== D-Roshan/CafeDeReduit/backups/IndexDbVerify.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Employees">
    <xs:complexType>
      <xs:sequence>
          <xs:element name="person" maxOccurs="10"> 
            <xs:complexType>
              <xs:sequence>
                <xs:element name = "FirstName" type="xs:string"> </xs:element>
                <xs:element name = "LastName" type="xs:string"> </xs:element>
                <xs:element name = "Position" type="xs:string"> </xs:element>
                <xs:element name = "Department" type="xs:string"> </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
      </xs:sequence>
      </xs:complexType>
</xs:element>
</xs:schema>

=== D-Roshan/CafeDeReduit/backups/IndexDb.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IndexDbVerify.xsd">

<person>
<FirstName> John </FirstName>
<LastName> Smith</LastName>
<Position> Clerk</Position>
<Department>Administration </Department>
</person>

<person>
<FirstName> Rita </FirstName>
<LastName> Koboshovsky</LastName>
<Position> Programmer</Position>
<Department> IT Department</Department>
</person>

<person>
<FirstName> Jane </FirstName>
<LastName> Doe</LastName>
<Position> Project Manager</Position>
<Department> IT Department</Department>
</person>

<person>
<FirstName> Shane </FirstName>
<LastName> Manilal</LastName>
<Position> Manager</Position>
<Department> Human Resource</Department>
</person>

</Employees>
