=== D-Roshan/CafeDeReduit/CafeDeReduit/DataStore/Abt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="AboutUs">
<xs:complexType>
<xs:sequence>

<xs:element name="CafeName" type="xs:string"/>
<xs:element name="AboutUsInfo" type="xs:string"/>

  <xs:element name="Founders">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" maxOccurs="5" minOccurs="0">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:integer" name="born" />
                <xs:attribute type="xs:integer" name="death" use="optional"/>
                <xs:attribute type="xs:string" name="Photo" use="optional"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

<xs:element name="address" >

<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="postalCode" type="xs:string"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>

</xs:element>

<xs:element name="emails">
<xs:complexType>
<xs:sequence>
<xs:element name="mail" maxOccurs="5"> 

<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="type" type="xs:string"/>
<xs:attribute name="officer" type="xs:string"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>

</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== D-Roshan/CafeDeReduit/CafeDeReduit/DataStore/Abt.xml
<?xml version="1.0" encoding="UTF-8"?>
<AboutUs xsi:noNamespaceSchemaLocation="Abt.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <CafeName>Cafe de Reduit</CafeName>
  <AboutUsInfo>Some Data About us... Tadada </AboutUsInfo>
  <Founders>
    <name born="1920" death="2010" Photo="FounderAmbanio.jpg">Mukesha Ambanio</name>
    <name born="1899" >Amitesh Bheekhee</name>
    <name born="1900">Dineshraj Boyjoo</name>
  </Founders>
  <address postalCode="BACNRD4152"> Bassin Canard, State House Avenue, Reduit Moka, Republic of Mauritius </address>
<emails>
<mail type="senior" > admin@reduitcafe.mu</mail>
<mail type="sales" > sales@reduitcafe.mu</mail>
<mail type="recruit" > recruitment@reduitcafe.mu</mail>
<mail type="complaint" > contactUs@reduitcafe.mu</mail>
</emails>
</AboutUs>
